<?php

namespace lesha724\bootstraptree;
use yii\helpers\Html;
use yii\helpers\Json;
use yii\web\View;

/**
 * This is just an example.
 */
class TreeView extends \yii\base\Widget
{
    public static $autoIdPrefix = 'wbtreeview_';
    /**
     * @var array additional HTML attributes that will be rendered in the div tag.
     */
    public $htmlOptions=[];
    /**
     * @var array additional options that can be passed to the constructor of the treeview js object.
     */
    public $options=[];

    protected $_id;

    public function init(){
        parent::init();

        if(isset($this->htmlOptions['id']))
            $this->_id=$this->htmlOptions['id'];
        else
            $this->_id=$this->htmlOptions['id']=$this->getId();
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        $view = $this->getView();
        TreeViewAsset::register($view);

        $options=$this->options===[]?'{}' : Json::encode($this->options);
        $view->registerJs('$("#' . $this->_id . '").treeview( ' .$options .')', View::POS_READY);

        return $this->_runWidget();
    }

    /**
     * Вывод виджета
     * @return string html widget
     */
    protected function _runWidget()
    {
        $html = Html::beginTag('div',$this->htmlOptions);
        $html .= Html::endTag('div');

        return $html;
    }
}
